name = "supplier-hub"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "supplier-hub"

[env.preview]
name = "supplier-hub-preview"

[build]
command = "npm run build"
pages_build_output_dir = ".next"
