name = "supplier-hub-mobile-ui"
compatibility_date = "2024-01-01"

# Конфигурация для Cloudflare Pages
pages_build_output_dir = "out"

[build]
command = "npm run build"

# Переменные окружения (будут настроены в панели Cloudflare)
[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://supplier-hub-mobile-ui1.pages.dev"
